server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:contract-manager-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: su
    password:
    driver-class-name: org.h2.Driver
    schema: db-schema
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: db-schema
        # For H2 to behave more like PostgreSQL (if your prod DB is Postgres)
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    defaultSchema: db-schema
    enabled: true
    baseline-on-migrate: true
