server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:contact_manager_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: su
    password:
    driver-class-name: org.h2.Driver
    schema: schema_db
  jpa:
    hibernate:
      ddl-auto: none # to avoid clashing with flyway
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: schema_db
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    defaultSchema: schema_db
    enabled: true
    baseline-on-migrate: true
