--CREATE TABLE CONTACT_ENTERPRISE (
--    contact_id UUID NOT NULL,
--    enterprise_id UUID NOT NULL,
--
--    CONSTRAINT pk_contact_enterprise PRIMARY KEY (contact_id, enterprise_id),
--
--    CONSTRAINT fk_contact_enterprise_contact_id  FOREIGN KEY (contact_id) REFERENCES CONTACT(contract_id),
--    CONSTRAINT fk_contact_enterprise_enterprise_id FOREIGN KEY (enterprise_id) REFERENCES ENTERPRISE(enterprise_id)
--);